### ISSUE TITLE
Link validator errors

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#262]
```
/Users/warren/DEV/vitepress-docs/libs/link-validator.js:161
          if (url.indexOf('http://') === -1 && url.indexOf('https://') === -1) {
                  ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at loadLinks (/Users/warren/DEV/vitepress-docs/libs/link-validator.js:161:19)
    at start (/Users/warren/DEV/vitepress-docs/libs/link-validator.js:231:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
```

**Comment by wkande** [comment]
script updated
